name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Nodejs
      uses: actions/setup-node@v4
    - run: cd cli && npm install
    - run: cd cli && npm test